2017-06-13 17:21:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ограничение "FK_CONNECTION_ON_AUTH_USER" уже существует
Constraint "FK_CONNECTION_ON_AUTH_USER" already exists; SQL statement:
--FK CONNECTION.DRIVER -> DRIVER.CODE
ALTER TABLE CONNECTION
  ADD CONSTRAINT FK_CONNECTION_ON_AUTH_USER FOREIGN KEY (DRIVER) REFERENCES DRIVER(CODE) [90045-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:109)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:77)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-06-13 17:21:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неверное количество столбцов
Column count does not match; SQL statement:
INSERT INTO CONNECTION VALUES(
  'jdbc:h2:D:\VEBDLC-pilot\target\dac-veb\db', 'H2', 'sa', '', 'PUBLIC', 1
) [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-06-13 17:22:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Таблица "DRIVER" уже существует
Table "DRIVER" already exists; SQL statement:
--=========================================================================================================
--============================================DRIVER===================================================
--=========================================================================================================
CREATE TABLE DRIVER(
  CODE                            VARCHAR(50)                   PRIMARY KEY,
  DESCRIPTION                     VARCHAR(256)                  DEFAULT NULL
) [42101-194]
2017-06-13 17:22:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неверное количество столбцов
Column count does not match; SQL statement:
INSERT INTO CONNECTION VALUES(
  'jdbc:h2:D:\VEBDLC-pilot\target\dac-veb\db', 'H2', 'sa', '', 'PUBLIC', 1
) [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-06-13 17:22:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неверное количество столбцов
Column count does not match; SQL statement:
INSERT INTO CONNECTION VALUES(
  'jdbc:h2:D:\VEBDLC-pilot\target\dac-veb\db', 'H2', 'sa', '', 'PUBLIC', 1
) [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-06-14 15:13:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Таблица "TEST" уже существует
Table "TEST" already exists; SQL statement:
create table test(id BIGINT primary key) [42101-194]
2017-06-14 15:14:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "CREATE TABLE TEST(ID BIGINT PRIMARY KEY, DATA VARCHAR(50) NULLABLE[*]) "; ожидалось "FOR, UNSIGNED, NOT, NULL, AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE TEST(ID BIGINT PRIMARY KEY, DATA VARCHAR(50) NULLABLE[*]) "; expected "FOR, UNSIGNED, NOT, NULL, AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
create table test(id BIGINT primary key, data varchar(50) nullable) [42001-194]
2017-06-14 15:14:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO TEST (1[*]) "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO TEST (1[*]) "; expected "identifier"; SQL statement:
insert into test (1) [42001-194]
2017-06-14 15:15:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO TEST (ID)(1[*]) "; ожидалось "(, WITH, SELECT, FROM"
Syntax error in SQL statement "INSERT INTO TEST (ID)(1[*]) "; expected "(, WITH, SELECT, FROM"; SQL statement:
insert into test (id)(1) [42001-194]
2017-06-14 15:17:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT COUNT* FROM TEST [*]"; ожидалось "., (, USE, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"
Syntax error in SQL statement "SELECT COUNT* FROM TEST [*]"; expected "., (, USE, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:
select count* from test [42001-194]
2017-06-14 15:17:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT COUNT* FROM TEST [*]"; ожидалось "., (, USE, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"
Syntax error in SQL statement "SELECT COUNT* FROM TEST [*]"; expected "., (, USE, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:
select count* from test [42001-194]
2017-06-14 16:21:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "c" не найден
Column "c" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:21:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "c" не найден
Column "c" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3148)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:21:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "c" не найден
Column "c" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:21:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "c" не найден
Column "c" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3148)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:21:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "c" не найден
Column "c" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:21:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "c" не найден
Column "c" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:21:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "c" не найден
Column "c" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:23:27 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]" [50000-193]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:379)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:362)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2923)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2468)
	at org.h2.engine.Database.open(Database.java:695)
	at org.h2.engine.Database.openDatabase(Database.java:273)
	at org.h2.engine.Database.<init>(Database.java:267)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:115)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:99)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at ru.shipilov.diplom.logic.Connector.<init>(Connector.java:25)
	at ru.shipilov.diplom.logic.Main.main(Main.java:9)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]" [50000-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:348)
	... 20 more
2017-06-14 16:23:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:23:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3148)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:23:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:23:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3148)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:23:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:23:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:23:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:93)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3148)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3148)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3148)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3148)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:26:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "C" не найден
Column "C" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:676)
	at ru.shipilov.diplom.logic.Connector.getTable(Connector.java:98)
	at ru.shipilov.diplom.logic.Main.main(Main.java:14)
2017-06-14 16:27:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "+name+" не найден
Column "+name+" not found; SQL statement:
SELECT
                            CASE WHEN COUNT(CODE ) IS NULL
                              THEN 0 
                            ELSE COUNT("+name+")
                            END AS C
                            FROM AUTHORITY [42122-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:146)
	at org.h2.expression.Aggregate.optimize(Aggregate.java:379)
	at org.h2.expression.Function.optimize(Function.java:2306)
	at org.h2.expression.Alias.optimize(Alias.java:51)
	at org.h2.command.dml.Select.prepare(Select.java:853)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-06-14 16:28:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT
                            CASE WHEN COUNT(CODE ) IS NULL
                              THEN 0  AS[*] C
                            ELSE COUNT(CODE )  AS C
                            END AS C
                            FROM AUTHORITY"; ожидалось "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, WHEN, ELSE, END"
Syntax error in SQL statement "SELECT
                            CASE WHEN COUNT(CODE ) IS NULL
                              THEN 0  AS[*] C
                            ELSE COUNT(CODE )  AS C
                            END AS C
                            FROM AUTHORITY"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, WHEN, ELSE, END"; SQL statement:
SELECT
                            CASE WHEN COUNT(CODE ) IS NULL
                              THEN 0  AS C
                            ELSE COUNT(CODE )  AS C
                            END AS C
                            FROM AUTHORITY [42001-194]
2017-06-14 16:28:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT
                            CASE WHEN COUNT(CODE ) IS NULL
                              THEN 0  AS[*] C
                            ELSE COUNT(CODE )  AS C
                            END AS C
                            FROM AUTHORITY"; ожидалось "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, WHEN, ELSE, END"
Syntax error in SQL statement "SELECT
                            CASE WHEN COUNT(CODE ) IS NULL
                              THEN 0  AS[*] C
                            ELSE COUNT(CODE )  AS C
                            END AS C
                            FROM AUTHORITY"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, WHEN, ELSE, END"; SQL statement:
SELECT
                            CASE WHEN COUNT(CODE ) IS NULL
                              THEN 0  AS C
                            ELSE COUNT(CODE )  AS C
                            END AS C
                            FROM AUTHORITY [42001-194]
2017-06-14 16:28:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT
                            CASE WHEN COUNT(CODE ) IS NULL
                              THEN 0  AS[*] C
                            ELSE COUNT(CODE )
                            END AS C
                            FROM AUTHORITY"; ожидалось "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, WHEN, ELSE, END"
Syntax error in SQL statement "SELECT
                            CASE WHEN COUNT(CODE ) IS NULL
                              THEN 0  AS[*] C
                            ELSE COUNT(CODE )
                            END AS C
                            FROM AUTHORITY"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, WHEN, ELSE, END"; SQL statement:
SELECT
                            CASE WHEN COUNT(CODE ) IS NULL
                              THEN 0  AS C
                            ELSE COUNT(CODE )
                            END AS C
                            FROM AUTHORITY [42001-194]
2017-06-14 16:28:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "ROLE_ADMIN"
Data conversion error converting "ROLE_ADMIN" [22018-193]
2017-06-14 16:29:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "H2"
Data conversion error converting "H2" [22018-193]
2017-06-14 16:29:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "ROLE_ADMIN"
Data conversion error converting "ROLE_ADMIN" [22018-193]
2017-06-14 17:04:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "H2"
Data conversion error converting "H2" [22018-193]
2017-06-14 17:05:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "ROLE_ADMIN"
Data conversion error converting "ROLE_ADMIN" [22018-193]
2017-06-14 17:05:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:05:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:05:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:05:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "H2"
Data conversion error converting "H2" [22018-193]
2017-06-14 17:05:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:05:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:07:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "ROLE_ADMIN"
Data conversion error converting "ROLE_ADMIN" [22018-193]
2017-06-14 17:07:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:07:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:07:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:07:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "H2"
Data conversion error converting "H2" [22018-193]
2017-06-14 17:07:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:07:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:08:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "ROLE_ADMIN"
Data conversion error converting "ROLE_ADMIN" [22018-193]
2017-06-14 17:08:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:08:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:08:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:08:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "H2"
Data conversion error converting "H2" [22018-193]
2017-06-14 17:08:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:08:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:08:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "ROLE_ADMIN"
Data conversion error converting "ROLE_ADMIN" [22018-193]
2017-06-14 17:08:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:08:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:08:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:08:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "H2"
Data conversion error converting "H2" [22018-193]
2017-06-14 17:08:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:09:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:09:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT CASE WHEN COUNT(DESCRIPTION) IS NULL   THEN[*] 0ELSE COUNT(DESCRIPTION)END AS C FROM AUTHORITY"
Syntax error in SQL statement "SELECT CASE WHEN COUNT(DESCRIPTION) IS NULL   THEN[*] 0ELSE COUNT(DESCRIPTION)END AS C FROM AUTHORITY"; SQL statement:
SELECT CASE WHEN COUNT(DESCRIPTION) IS NULL   THEN 0ELSE COUNT(DESCRIPTION)END AS C FROM AUTHORITY [42000-193]
2017-06-14 17:09:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT CASE WHEN COUNT(DESCRIPTION) IS NULL   THEN[*] 0ELSE COUNT(DESCRIPTION)END AS C FROM DRIVER"
Syntax error in SQL statement "SELECT CASE WHEN COUNT(DESCRIPTION) IS NULL   THEN[*] 0ELSE COUNT(DESCRIPTION)END AS C FROM DRIVER"; SQL statement:
SELECT CASE WHEN COUNT(DESCRIPTION) IS NULL   THEN 0ELSE COUNT(DESCRIPTION)END AS C FROM DRIVER [42000-193]
2017-06-14 17:10:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:11:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:11:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:11:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:11:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:11:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:11:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:15:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:15:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:15:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:15:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:15:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:15:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:15:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:15:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:18:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:20:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:20:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:20:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:20:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:20:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:20:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:22:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:22:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:22:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:22:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:22:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:22:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:22:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:25:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:25:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:25:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:25:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:25:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:25:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:25:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:26:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:26:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:26:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:26:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:26:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:26:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:26:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:26:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:27:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:27:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:27:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:27:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:27:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:27:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:28:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:28:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:28:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:28:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:28:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:28:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:28:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:28:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:29:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:29:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:29:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:29:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:29:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:29:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:29:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:29:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:29:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:29:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:29:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:29:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:29:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:30:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:30:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:30:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:30:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:30:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:30:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:30:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:44:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:44:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:44:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:44:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:44:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:44:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:44:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:47:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:47:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:47:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:47:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:47:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:47:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 17:47:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:30:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:31:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:31:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:31:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:31:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:31:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:31:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:32:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:35:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:35:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:35:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:35:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:35:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:35:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-193]
2017-06-14 23:36:08 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]" [50000-193]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:379)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:362)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2923)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2468)
	at org.h2.engine.Database.open(Database.java:695)
	at org.h2.engine.Database.openDatabase(Database.java:273)
	at org.h2.engine.Database.<init>(Database.java:267)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:115)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:99)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at ru.shipilov.diplom.logic.Connector.<init>(Connector.java:24)
	at ru.shipilov.diplom.logic.Main.main(Main.java:9)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]" [50000-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:348)
	... 20 more
2017-06-15 15:06:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "SALARY" не найден
Column "SALARY" not found; SQL statement:
select salary from test [42122-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:146)
	at org.h2.command.dml.Select.prepare(Select.java:853)
	at org.h2.command.Parser.prepareCommand(Parser.java:261)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2017-06-15 15:30:06 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]" [50000-193]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:379)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:362)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2923)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2468)
	at org.h2.engine.Database.open(Database.java:695)
	at org.h2.engine.Database.openDatabase(Database.java:273)
	at org.h2.engine.Database.<init>(Database.java:267)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:115)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:99)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at ru.shipilov.diplom.logic.Connector.<init>(Connector.java:26)
	at ru.shipilov.diplom.logic.Main.main(Main.java:8)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]" [50000-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:348)
	... 20 more
2017-06-15 15:30:15 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]" [50000-193]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:379)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:362)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2923)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2468)
	at org.h2.engine.Database.open(Database.java:695)
	at org.h2.engine.Database.openDatabase(Database.java:273)
	at org.h2.engine.Database.<init>(Database.java:267)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:115)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:99)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at ru.shipilov.diplom.logic.Connector.<init>(Connector.java:26)
	at ru.shipilov.diplom.logic.Main.main(Main.java:8)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]" [50000-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.193/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:348)
	... 20 more
2017-06-15 15:37:06 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.194/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2474)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.test(WebApp.java:885)
	at org.h2.server.web.WebApp.process(WebApp.java:220)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:169)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.194/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.194/7]" [50000-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 28 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:D:/Users/sasha/Desktop/diplom/db/db.mv.db [1.4.194/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 23 more
